runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: templates/main_page.html
  upload: templates/main_page.html
- url: /static/upload-images.*
  static_dir: static/upload-images
- url: /static.*
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
